# i3 key bindings
# this file should be included in ~/.config/i3/config

# restart i3 
bindsym $mod+Shift+r restart

# kill window
bindsym $mod+w kill 
bindsym --release $mod+Shift+x exec xkill

# exit/lock options
bindsym $mod+Ctrl+q exec poweroff
bindsym $mod+Shift+q exec i3-msg exit
bindsym $mod+Escape exec --no-startup-id ~/.config/i3/scripts/blur-lock

# launchers
bindsym $mod+space exec --no-startup-id rofi -modi drun -show drun \
		-config ~/.config/rofi/rofidmenu.rasi
bindsym $mod+d exec --no-startup-id rofi -show combi \
		-config ~/.config/rofi/rofidmenu.rasi

bindsym $mod+Return exec xfce4-terminal
bindsym $mod+e exec Thunar
bindsym $mod+a exec pavucontrol
bindsym $mod+b exec firefox
bindsym $mod+c exec brave
bindsym $mod+Shift+b exec blueman-manager
bindsym $mod+Shift+s exec flameshot gui

# fullscreen
bindsym $mod+f fullscreen toggle
# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# tiling
# change focus 
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# resize window (you can also use the mouse for that)
mode "resize" {
        bindsym h resize shrink width 10 px or 10 ppt
        bindsym j resize grow height 10 px or 10 ppt
        bindsym k resize shrink height 10 px or 10 ppt
        bindsym l resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

## workspaces
# Assign a program to a workspace and focus to them on startup:
# assign [class="Xfce4-terminal"] workspace number 1

# switch/iterate between workspaces
bindsym $mod+Tab workspace next

# switch to workspace
bindsym $mod+1 workspace number 1
bindsym $mod+2 workspace number 2
bindsym $mod+3 workspace number 3
bindsym $mod+4 workspace number 4
bindsym $mod+5 workspace number 5
bindsym $mod+6 workspace number 6
bindsym $mod+7 workspace number 7
bindsym $mod+8 workspace number 8
bindsym $mod+9 workspace number 9
bindsym $mod+0 workspace number 10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number 1
bindsym $mod+Shift+2 move container to workspace number 2
bindsym $mod+Shift+3 move container to workspace number 3
bindsym $mod+Shift+4 move container to workspace number 4
bindsym $mod+Shift+5 move container to workspace number 5
bindsym $mod+Shift+6 move container to workspace number 6
bindsym $mod+Shift+7 move container to workspace number 7
bindsym $mod+Shift+8 move container to workspace number 8
bindsym $mod+Shift+9 move container to workspace number 9
bindsym $mod+Shift+0 move container to workspace number 10

### Top row (functional keys)
# Use pactl to adjust volume in PulseAudio.
#set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +7% && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -7% && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status
# use brightnessctl to adjust screen brightness
bindsym XF86MonBrightnessUp exec brightnessctl set +10%
bindsym XF86MonBrightnessDown exec brightnessctl set 10%- 
# other top row keys
bindsym XF86Calculator exec --no-startup-id galculator

# reserved shortcuts
# meta+m for mic mute @Discord

